Update dummy files (#5)

diff --git a/.github/workflows/dummy.yml b/.github/workflows/dummy.yml
--- a/.github/workflows/dummy.yml
+++ b/.github/workflows/dummy.yml
@@ -9,4 +9,19 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
-      - run: echo "This is a dummy CI failure"; exit 1
+      - name: Create sample artifact files
+        run: |
+          echo "test failure" > failure.txt
+          echo "sample log file" > log.txt
+      - name: Upload sample artifact
+        # if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: sample-artifact
+          path: |
+            failure.txt
+            log.txt
+      - name: Fail the workflow
+        run: |
+          echo "This is a dummy CI failure"
+          exit 1
